### ISSUE TITLE
Optimizacion De Imagenes

### ISSUE THREAD

**Issue by nabucodonosor7** [UntitleCodes/Portfolio#2]
Es necesario optimizar las imágenes que forman parte tanto de las cartas, como de los articulos mejorando el tiempo de carga, para ello kraken en una alternativa al problema, tambien seria genial publicar diferentes optimizadores y publicar capturas de los tiempos de carga.

**Comment by jose1937JS** [comment]
y webpack ??

**Comment by nabucodonosor7** [comment]
Interesante, sin embargo por motivos de tiempo dejemos eso como futura mejora. Pero me parece Genial una implementacion completa de loaders para todo el portafolio

**Comment by nabucodonosor7** [comment]
# LINK DE PAGINAS DE OPTIMIZACION ONLINE
http://optimizilla.com/es/
